# Generated by Django 2.2 on 2019-05-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='Company', max_length=255)),
                ('title', models.CharField(default='Title', max_length=255)),
                ('description', models.CharField(default='Description', max_length=990)),
                ('requirements', models.CharField(default='Requirements', max_length=990)),
            ],
        ),
    ]
