# Generated by Django 2.2 on 2019-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(default='Description', max_length=9900),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.CharField(default='Requirements', max_length=9900),
        ),
    ]
