# Generated by Django 2.2 on 2019-06-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20190617_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='applied', max_length=255),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
